//
// Generated file, do not edit! Created by opp_msgc 4.2 from messages/access_data.msg.
//

#ifndef _ACCESS_DATA_M_H_
#define _ACCESS_DATA_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/access_data.msg</tt> by opp_msgc.
 * <pre>
 * message access_data{
 *         unsigned long chunk;
 *         }
 * </pre>
 */
class access_data : public ::cMessage
{
  protected:
    unsigned long chunk_var;

  private:
    void copy(const access_data& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const access_data&);

  public:
    access_data(const char *name=NULL, int kind=0);
    access_data(const access_data& other);
    virtual ~access_data();
    access_data& operator=(const access_data& other);
    virtual access_data *dup() const {return new access_data(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned long getChunk() const;
    virtual void setChunk(unsigned long chunk);
};

inline void doPacking(cCommBuffer *b, access_data& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, access_data& obj) {obj.parsimUnpack(b);}


#endif // _ACCESS_DATA_M_H_
