//
// Generated file, do not edit! Created by opp_msgc 4.2 from messages/ccn_data.msg.
//

#ifndef _CCN_DATA_M_H_
#define _CCN_DATA_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/ccn_data.msg</tt> by opp_msgc.
 * <pre>
 * message ccn_data{
 * 	unsigned long chunk;
 * 	double d = 0;
 * 	double hops = 0;
 * 	unsigned long repository;
 * }
 * </pre>
 */
class ccn_data : public ::cMessage
{
  protected:
    unsigned long chunk_var;
    double d_var;
    double hops_var;
    unsigned long repository_var;

  private:
    void copy(const ccn_data& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ccn_data&);

  public:
    ccn_data(const char *name=NULL, int kind=0);
    ccn_data(const ccn_data& other);
    virtual ~ccn_data();
    ccn_data& operator=(const ccn_data& other);
    virtual ccn_data *dup() const {return new ccn_data(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned long getChunk() const;
    virtual void setChunk(unsigned long chunk);
    virtual double getD() const;
    virtual void setD(double d);
    virtual double getHops() const;
    virtual void setHops(double hops);
    virtual unsigned long getRepository() const;
    virtual void setRepository(unsigned long repository);
};

inline void doPacking(cCommBuffer *b, ccn_data& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ccn_data& obj) {obj.parsimUnpack(b);}


#endif // _CCN_DATA_M_H_
