//
// Generated file, do not edit! Created by opp_msgc 4.2 from messages/local.msg.
//

#ifndef _LOCAL_M_H_
#define _LOCAL_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/local.msg</tt> by opp_msgc.
 * <pre>
 * message local{
 *     unsigned int file_name;
 * }
 * </pre>
 */
class local : public ::cMessage
{
  protected:
    unsigned int file_name_var;

  private:
    void copy(const local& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const local&);

  public:
    local(const char *name=NULL, int kind=0);
    local(const local& other);
    virtual ~local();
    local& operator=(const local& other);
    virtual local *dup() const {return new local(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getFile_name() const;
    virtual void setFile_name(unsigned int file_name);
};

inline void doPacking(cCommBuffer *b, local& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, local& obj) {obj.parsimUnpack(b);}


#endif // _LOCAL_M_H_
